name: lib-manage-admin-docker

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v2

      - name: set-up-jdk17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: build-project
        run: mvn clean install -Dmaven.test.skip=true

      - name: set-up-docker-buildx
        uses: docker/setup-buildx-action@v2

      - name: cache-docker-layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: login-to-dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: extract-version
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: build-and-push-docker-image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .docker/Dockerfile
          push: true
          tags: |
            zaizaihan/lib-manage-admin:${{ env.VERSION }}
            zaizaihan/lib-manage-admin:latest
          platforms: linux/amd64,linux/arm64